name: SEMBEQ Microprogrammes
favicon: null
layout_spectrum: 0.75106
typography_spectrum: 0.06976905069313943
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0baf93'
    - '#001d1a'
    - '#ffffff'
    - '#91cebc'
    - '#485b58'
  brandStrength: 0.09460945380851626
  lightness: 0.7381932709831744
  saturation: 0.5862669018097222
  rhythmicContrast: 0.4336542235687375
purpose: []
